# Generated by Django 5.1.6 on 2025-02-19 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('contact_info', models.EmailField(max_length=254)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('NLP', 'Natural Language Processing'), ('CV', 'Computer Vision'), ('RL', 'Reinforcement Learning'), ('OTHER', 'Other')], max_length=5)),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('PT', 'PyTorch'), ('TF', 'TensorFlow'), ('KRS', 'Keras'), ('OTHER', 'Other')], max_length=5)),
                ('version', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_uploaded', to='models_api.modelauthor')),
            ],
        ),
        migrations.CreateModel(
            name='ModelBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('benchmark_date', models.DateTimeField(auto_now_add=True)),
                ('hardware_used', models.CharField(max_length=200)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='models_api.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('license_key', models.DecimalField(decimal_places=2, max_digits=10)),
                ('download_link', models.URLField()),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_api.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='UsageScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField()),
                ('usage_frequency', models.IntegerField(default=0)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_scenarios', to='models_api.aimodel')),
            ],
        ),
    ]
