# Generated by Django 5.1.6 on 2025-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
