# Generated by Django 5.1.6 on 2025-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_api', '0002_alter_aimodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpurchase',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
